@extends('layouts.app')
@section('title','Servers')
@section('content')
<div style="display:flex;justify-content:space-between;align-items:flex-end;gap:20px;margin-bottom:24px"><div><div class="mp-eyebrow">Infrastructure</div><h1>Servers</h1><p class="mp-sub" style="margin-bottom:0">Manage the VPS machines connected to your mPanel control plane.</p></div><a href="{{ route('servers.create') }}" class="mp-primary-btn">＋ Add server</a></div>
<div class="mp-card" style="padding:0;overflow:hidden"><div class="mp-table-wrap"><table class="mp-table"><thead><tr><th>Server</th><th>Address</th><th>Status</th><th>Resources</th><th>Last seen</th><th></th></tr></thead><tbody>
@forelse($servers as $server)<tr><td><a class="mp-link" href="{{ route('servers.show',$server) }}"><strong>{{ $server->name }}</strong></a><small>{{ $server->hostname ?: 'No hostname' }}</small></td><td>{{ $server->ip_address }}:{{ $server->port }}</td><td><span class="mp-status {{ $server->status }}">{{ ucfirst($server->status) }}</span></td><td><div class="mp-resource-line">CPU {{ $server->cpu_percent ?? '—' }}%</div><div class="mp-resource-line">RAM {{ $server->memory_percent ?? '—' }}%</div><div class="mp-resource-line">Disk {{ $server->disk_percent ?? '—' }}%</div></td><td>{{ $server->last_seen_at?->diffForHumans() ?? 'Never' }}</td><td><a class="mp-link" href="{{ route('servers.show',$server) }}">Manage →</a></td></tr>
@empty<tr><td colspan="6"><div style="padding:45px;text-align:center"><div style="font-size:35px;color:var(--brand)">◈</div><strong>No servers connected</strong><p class="mp-sub">Add your first Ubuntu VPS and connect it with the mPanel Agent.</p><a href="{{ route('servers.create') }}" class="mp-primary-btn">Add your first server</a></div></td></tr>@endforelse
</tbody></table></div></div>
@if($servers->hasPages())<div style="margin-top:18px">{{ $servers->links() }}</div>@endif
@endsection
@push('head')<style>
.mp-primary-btn{display:inline-flex;align-items:center;justify-content:center;gap:7px;padding:11px 16px;background:var(--brand);color:#fff!important;border-radius:11px;text-decoration:none;font-weight:800;border:0;cursor:pointer}.mp-table-wrap{overflow:auto}.mp-table{width:100%;border-collapse:collapse;min-width:820px}.mp-table th,.mp-table td{padding:15px 18px;border-bottom:1px solid var(--border);text-align:left;vertical-align:middle}.mp-table th{font-size:11px;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.mp-table td small{display:block;color:var(--muted);margin-top:3px}.mp-link{color:var(--brand);text-decoration:none;font-weight:700}.mp-status{display:inline-flex;padding:5px 9px;border-radius:999px;font-size:11px;font-weight:800;background:var(--brand-soft);color:var(--brand)}.mp-status.pending{background:#fff6df;color:#9a6a00}.mp-status.offline{background:#ffecec;color:#a52c2c}.mp-resource-line{font-size:12px;color:var(--muted)}
</style>@endpush
